// Dados da seção Doc Studio (bônus). Só conteúdo — a marcação fica no componente.

export const docStudioBenefits = [
  { title: "Feito pra sua rotina", text: "Documentos do dia a dia, prontos pra preencher." },
  { title: "Campos guiados", text: "Preencha e veja a folha se montar ao lado." },
  { title: "Cabeçalho profissional", text: "Seu nome e registro em cada documento." },
  { title: "Copiar ou imprimir", text: "Folha pronta pra copiar ou imprimir em A4/PDF." },
  { title: "Documento em branco", text: "Títulos editáveis e até 6 seções. Escreva do seu jeito." },
  { title: "Rascunho local", text: "Salvo no navegador, sem nuvem, é seu." },
] as const;

export const docStudioSteps = [
  "Escolha a profissão e o modelo",
  "Preencha os campos guiados",
  "Acompanhe o documento ao lado",
  "Copie ou imprima em A4/PDF",
] as const;

// Modelos da Psicopedagogia — reaproveitados na Neuropsicopedagogia (mesma lista).
const modelosPsicopedagogia = [
  "Documento em branco",
  "Declaração de comparecimento",
  "Recibo / declaração de pagamento",
  "Encaminhamento profissional",
  "Contrato / termo de prestação de serviço",
  "Autorização simples",
  "TCLE simplificado",
  "Devolutiva para família",
  "Relatório de acompanhamento",
  "Registro de sessão",
  "Encaminhamento orientativo",
  "Entrevista com família",
  "Entrevista com aprendente",
  "Entrevista com professor/escola",
  "Observação escolar",
  "Observação lúdica",
  "Devolutiva para escola",
  "Relatório de observação escolar",
  "Relatório individual AEE",
  "Plano de apoio escolar / PEI simplificado",
  "Autorização / contrato / declaração simples",
] as const;

export const docStudioProfessions = [
  {
    name: "Psicopedagogia",
    modelos: modelosPsicopedagogia,
    instrumentos: [
      "EOCA",
      "Observação lúdica — roteiro",
      "Roteiro de desempenho lógico-matemático",
      "Roteiro descritivo inicial/anual",
      "Levantamento de desempenho escolar",
      "Avaliação das capacidades básicas",
      "Entrevista inicial com professor",
      "Relatório do professor para intervenção",
      "Relatório de observação escolar — roteiro",
      "Ficha de cadastro",
      "Avaliação da coordenação motora fina",
      "Questionário de identificação do perfil",
      "Entrevista com aprendente — roteiro",
      "Entrevista detalhada com aluno",
      "Dados para sessão devolutiva",
      "Avaliação bimestral — Sala de Recursos",
      "Acompanhamento diário — Sala de Recursos",
    ],
  },
  {
    name: "Psicologia / Neuropsicologia",
    modelos: [
      "Documento em branco",
      "Declaração de comparecimento",
      "Recibo / declaração de pagamento",
      "Encaminhamento profissional",
      "Contrato / termo de prestação de serviço",
      "Autorização simples",
      "TCLE simplificado",
      "Síntese psicológica descritiva",
      "Relatório psicológico estruturado",
      "Relatório multiprofissional",
      "Registro de evolução / acompanhamento",
      "Encaminhamento orientativo",
      "Planejamento terapêutico inicial",
      "Parecer psicológico orientativo",
      "Devolutiva clínica em linguagem acessível",
      "Orientação à família/responsáveis",
      "Contrato terapêutico",
      "Autorização para atendimento de menor",
      "Protocolo de atendimento online",
      "Declaração",
    ],
    instrumentos: [
      "Anamnese infantil e adolescente",
      "Anamnese adulto",
      "Anamnese pré-cirúrgica bariátrica",
      "Ficha anamnese infantil breve",
      "Anamnese TCC",
      "Anamnese neuropsicológica infantil",
      "Anamnese neuropsicológica adulto",
      "Anamnese psicossocial",
    ],
  },
  {
    name: "Neuropsicopedagogia",
    modelos: modelosPsicopedagogia,
    instrumentos: [
      "EOCA",
      "Anamnese neuropsicopedagógica otimizada",
      "Entrevista contratual",
      "Ficha de encaminhamento",
      "Informe de devolução",
      "Anamnese neuropsicopedagógica detalhada",
    ],
  },
] as const;
