export const spreadsheets = [
  "ABC / ICA – Instrumento de Estilo de Aprendizagem",
  "ABLLS-R – Sistema de Avaliação de Linguagem",
  "AFLS – Sistema de Aprendizagem Funcional",
  "ANC – Avaliação Neurocognitiva",
  "APM-RAVEN – Matrizes progressivas avançadas de Raven",
  "ASRS-18 – Escala de Avaliação do Autismo",
  "ATA – Avaliação de Transtornos Autísticos",
  "BAI – Beck Anxiety Inventory",
  "BDI-2 – Beck Depression Inventory-II",
  "BHS – Beck Hopelessness Scale",
  "BINAUTI – Investigação da Sintomatologia Autística em Crianças",
  "Blocos de Corsi – Teste de Memória e Sequenciamento",
  "BPA-2 ( São Paulo ) – Bateria Psicológica para Avaliação da Atenção",
  "CARS – 2 – Childhood Autism Rating Scale",
  "CARS – Escala de Avaliação do Autismo Infantil",
  "CAT-Q – Questionário de Camuflagem Autista",
  "CDI – Inventário de Depressão Infantil",
  "CES-D – Escala Epidemiológica de Depressão",
  "Check-Dis – Dislexia",
  "Colúmbia – Escala de Maturidade Mental Colúmbia",
  "CONNERS – Escala de Avaliação de TDAH",
  "CPM-RAVEN – Matrizes Progressivas Coloridas de Raven",
  "CPS – Escala de Resolução Criativa de Problemas",
  "Cuida-SM – Instrumento de Saúde Mental",
  "DCDQ – Questionário de Coordenação",
  "DENVER II – Triagem do Desenvolvimento Infantil",
  "Discalculia – Avaliação de Dificuldades Matemáticas",
  "Disgrafia – Avaliação de Escrita",
  "Dislexia – Avaliação de Leitura e Escrita",
  "Dislexia – Pré-Escolar – Triagem de Riscos para Dislexia",
  "Disortografia – Avaliação de Erros Ortográficos",
  "EAB-E – Escala de Bem-Estar Escolar",
  "EAM – Escala de Ansiedade à Matemática",
  "ELE – Escala de Leitura e Escrita",
  "EPF-TDAH – Escala de Problemas de Foco",
  "Escala de Traço Ansiedade Infantil – Medida de Ansiedade Infantil",
  "ESDM – Escala de Sintomatologia Depressiva para Mestres",
  "Estilo de Aprendizagem – Identificação de Preferências",
  "ETA – Escala de Transtornos Autísticos",
  "ETDAH – AD – Escala de TDAH para Adolescentes",
  "ETDAH – CriAd – Escala de TDAH para Crianças e Adolescentes",
  "ETDAH – Pais (2 a 17) – Escala de TDAH para Pais",
  "ETDAH – Pais (Geral) – Versão Geral para Pais",
  "ETDAH-2 – Escala de TDAH – 2ª Edição",
  "Fluência Verbal – Teste de Produção Linguística",
  "GIFTS – Checklist para Altas Habilidades/Superdotação de Pfeiffer",
  "HAM-A – Escala de Ansiedade de Hamilton",
  "HAM-D – Escala de Depressão de Hamilton",
  "IAHSA – Inventário de Altas Habilidades e Superdotação para Adultos",
  "IAR – Índice de Avaliação Escolar",
  "IDADI – Inventário de Desenvolvimento Infantil",
  "IDHC – Inventário de Desenvolvimento de Habilidades Cognitivas",
  "IEP – Inventário de Estilos Parentais",
  "IHL – Inventário de Habilidades Linguísticas",
  "IHS-2 – Inventário de Habilidades Sociais",
  "IHSA – Del-Prette — Inventário de Habilidades Sociais para Adolescentes.",
  "IMA – Inventário de Motivação Acadêmica",
  "M-CHAT – Triagem para Autismo em Crianças",
  "MASC – Escala Multidimensional de Ansiedade",
  "NOMEA – Teste de Nomeação de Estímulos Alternados",
  "Perfil Sensorial 2 – Avaliação Sensorial Infantil",
  "PHQ-9 – Questionário de Saúde – Depressão",
  "PORTAGE – Sistema de Educação Infantil",
  "PROLEC – Avaliação dos Processos de Leitura",
  "PROTEA-R – Avaliação do Transtorno do Espectro Autista",
  "Q Fisher – Teste de Estilo de Aprendizagem",
  "QA– Quociente do Aspectro Autista",
  "QUATI – Questionário de Avaliação Tipológica",
  "R1 – Teste não Verbal de Inteligência",
  "RAADS-R – Escala Diagnóstica de Autismo Adulto",
  "RAVLT – Rey Auditory Verbal Learning Test",
  "REISMAN CREATIVITY – Observação de Habilidades Criativas",
  "SCAHSD – Identificação de Altas Habilidades/Superdotação",
  "SCARED-II – Escala de Ansiedade Infantil",
  "SDQ-Por – Questionário de Capacidades e Dificuldades",
  "SNAP-IV – Escala de Avaliação de TDAH",
  "SPALA – Triagem Auditiva e Linguística",
  "Span de Dígitos – Teste de Sequenciamento de Dígitos",
  "SRBCSS – Características Comportamentais de Crianças Superdotadas",
  "SRS-2 – Escala de Responsividade Social",
  "STROOP TEST – Teste de Atenção e Inibição Cognitiva",
  "TAC – Teste de Avaliação de Compreensão",
  "TCCAL – Teste Contrastivo de Compreensão Auditiva e de Leitura",
  "TDE-2 – Teste de Desempenho Escolar",
  "TENA – Teste Neuropsicológico para Aprendizagem",
  "Teste de Conhecimento Numérico",
  "THAS-C – Teste de Habilidades Sociais Infantil",
  "THCP – Teste de Habilidades e Conhecimento Pré-Alfabetização",
  "TIAH/S – Teste de Inteligência e Habilidades Sociais",
  "TOD – Avaliação de Transtorno Opositivo-Desafiador",
  "TOD-ODDRS – Transtorno Opositivo Desafiador (escala ODDRS)",
  "TOKEN TEST (versão reduzida) – Teste de Compreensão Auditiva",
  "Torre de Londres – Teste de Planejamento Cognitivo",
  "TRILHA – Pré-Escolar – Versão Infantil do TRILHA",
  "TRILHA – Teste de Raciocínio Lógico-Abstrato",
  "VB-MAPP (Avaliação) – Avaliação de Marcos do Comportamento Verbal",
  "VB-MAPP (Coleta de Dados) – Registro e Monitoramento de Habilidades",
  "Vineland-3 – Escalas Vineland de Comportamento Adaptativo",
  "WAIS-III – Escala de Inteligência Wechsler para Adultos",
  "WASI – Escala Wechsler Abreviada de Inteligência",
  "WISC-IV – Escala de Inteligência Wechsler Infantil"
] as const;
